site_name: Portfolio - Data Contract Docs

theme:
  name: material

plugins:
  - search
  - mermaid2
  - mkdocstrings

nav:

  - Home: index.md

  - Data Contract: data_contract.md

  - Transformations: transformations.md

  - Tests: tests.md
